name:                dep-eindopdracht
version:             0.1.0.0
github:              "StanMey/dep-eindopdracht"
license:             BSD3
author:              "Stan Mey"
maintainer:          "Stan.Meyberg@student.hu.nl"
copyright:           "2019 Stan Mey"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dep-eindopdracht#readme>

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src

executables:
  dep-eindopdracht-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dep-eindopdracht

tests:
  dep-eindopdracht-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dep-eindopdracht
